export const footerData = [
  { id: 1, name: 'FAQ', url: '/faq' },
  // { id: 1, name: 'About Us', url: '/about' },
  { id: 2, name: 'Careers', url: '/careers' },
  { id: 3, name: 'Press', url: '/press' },
  { id: 4, name: 'Contact Us', url: '/contact' },
  { id: 5, name: 'Privacy Policy', url: '/privacy' },
  { id: 6, name: 'Terms of Service', url: '/terms' },
  { id: 7, name: 'Help Center', url: '/help' },
  { id: 8, name: 'Cookie Policy', url: '/cookies' },
  { id: 9, name: 'Accessibility', url: '/accessibility' },
  { id: 10, name: 'Community Guidelines', url: '/guidelines' },
  { id: 11, name: 'Security', url: '/security' },
  { id: 12, name: 'Investor Relations', url: '/investors' },
  { id: 13, name: 'Copyright', url: '/copyright' },
  { id: 14, name: 'DMCA', url: '/dmca' },
  { id: 15, name: 'Advertising', url: '/advertising' },
  // { id: 16, name: 'Affiliate Program', url: '/affiliate' },
  // { id: 17, name: 'Sitemap', url: '/sitemap' },
  // { id: 18, name: 'Blog', url: '/blog' },
  // { id: 19, name: 'Feedback', url: '/feedback' },
  // { id: 20, name: 'Beta Program', url: '/beta' },
];
